export enum SERVER_ERROR_TYPES {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  METHOD_NOT_SUPPORTED = "METHOD_NOT_SUPPORTED",
  UNPROCESSABLE_CONTENT = "UNPROCESSABLE_CONTENT",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  CLIENT_CLOSED_REQUEST = "CLIENT_CLOSED_REQUEST",
  TIMEOUT = "TIMEOUT",
}

export enum API_ERROR_TYPES {
  AUTH_CHECK_ERROR = "AUTH_CHECK_FAILED",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",
  INSUFFICIENT_CREDITS = "INSUFFICIENT_CREDITS",
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
}

export enum DB_ERROR_TYPES {
  DB_QUERY_ERROR = "DB_QUERY_ERROR",
}

export enum CLIENT_ERROR_TYPES {
  INPUT_PARSE_ERROR = "INPUT_PARSE_ERROR",
  OUTPUT_PARSE_ERROR = "OUTPUT_PARSE_ERROR",
  VALIDATION_ERROR = "ZOD_VALIDATION_FAILED",
  REACT_CONTEXT_ERROR = "HOOK_USED_IN_WRONG_FILE",
  NO_ENTRY_POINT = "ENTRY_POINT_MISSING",
  INVALID_INPUTS = "INVALID_WORKFLOW:INPUT",
  NO_WORKFLOWS = "NO_WORKFLOWS", 
  CREATE_WORKFLOW_ERROR = "CREATE_WORKFLOW_ERROR",
  TASK_NOT_FOUND_ERROR = "TASK_NOT_FOUND",
  WORKFLOW_NOT_IN_DRAFT_ERROR = "WORKFLOW_STATUS_NOT_DRAFT",
  NO_EXECUTION_PLAN = "NO_EXECUTION_PLAN_AVAILABLE",
}
