import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppThemeProvider from "@/components/provider/app-theme-provider";
import AuthProvider from "@/components/provider/auth-provider";
import ReactQueryProvider from "@/components/provider/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <ReactQueryProvider>
            <AppThemeProvider>{children}</AppThemeProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
