import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppThemeProvider from "@/components/provider/app-theme-provider";
import AuthProvider from "@/components/provider/auth-provider";
import ReactQueryProvider from "@/components/provider/react-query-provider";
import { register } from "@/env";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let isRegistered = false;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // register env variables
  if (!isRegistered) {
    await register();
    isRegistered = true;
  }

  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <ReactQueryProvider>
            <AppThemeProvider>
              {children}
              <Toaster />
            </AppThemeProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
