export enum API_ERROR_TYPES {
  AUTH_CHECK_ERROR = "AUTH_CHECK_FAILED",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",
  INSUFFICIENT_CREDITS = "INSUFFICIENT_CREDITS",
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  BAD_REQUEST = "BAD_REQUEST",
}
