import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ExecutionLog } from '@/db/schema';
import React from 'react'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { cn } from '@/lib/utils';
import { LogLevel } from '@/actions/execution/types/log';

type Props = {
    logs?: ExecutionLog[];
}

const LogViewer = ({ logs }: Props) => {
    if (!logs || logs.length === 0) return null;
    return (
        <Card className='w-full'>
            <CardHeader className='rounded-lg border-b py-4 bg-gray-50 dark:bg-background'>
                <CardTitle className='text-base'>Logs</CardTitle>
                <CardDescription className="tetx-muted-forground text-sm">Logs generated by this phase</CardDescription>
            </CardHeader>

            <CardContent className='p-0'>
                <Table>
                    <TableHeader className="text-muted-foreground
                    text-sm">
                        <TableRow>
                            <TableHead>Time</TableHead>
                            <TableHead>Level</TableHead>
                            <TableHead>Message</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {logs.map((log) => (
                            <TableRow key={log.id} className="text-muted-foreground">
                                <TableCell className='text-xs text-muted-foreground p-[2px] pl-4'>
                                    {new Date(log.timestamp).toISOString()}</TableCell>
                                <TableCell
                                    width={80} className={cn("uppercase font-bold p-[3px] text-xs pl-4", (log.logLevel as LogLevel) === "error" && "text-destructive", (log.logLevel as LogLevel) === "info" && "text-primary ")}>{log.logLevel}</TableCell>
                                <TableCell className='text-sm flex-1 p-[3px] pl-4'>{log.message}
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </CardContent >
        </Card >
    )
}

export default LogViewer