import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import React from 'react'

type Props = {
    title: string;
    subtitle: string;
    paramsJSON: string | null;
}

const ParameterViewer = ({ title, subtitle, paramsJSON }: Props) => {
    const params = paramsJSON ? JSON.parse(paramsJSON) : undefined;
    return (
        <Card>
            <CardHeader className='rounded-lg border-b py-4 bg-gray-50 dark:bg-background'>
                <CardTitle className='text-base'>{title}</CardTitle>
                <CardDescription className="tetx-muted-forground text-sm">{subtitle}</CardDescription>
            </CardHeader>

            <CardContent className='py-4'>

                <div className='flex flex-col gap-2'>
                    {(!params || Object.keys(params).length === 0) && (

                        <p className="text-muted-foreground text-sm">No parameters generated by phase</p>
                    )}

                    {params && Object.entries(params).map(([key, value]) => (
                        <div key={key} className="flex items-center justify-between space-y-1">
                            <p className="text-sm text-muted-foreground flex-1 basis-1/3">{key}</p>

                            <Input readOnly className='flex-1 basis-2/3' value={value as string} />
                        </div>
                    ))}
                </div>
            </CardContent>

        </Card>
    )
}

export default ParameterViewer