export type Testimonial = {
  name: string;
  role: string;
  company: string;
  avatar: string;
  quote: string;
  rating: number;
  className?: string; // For bento grid grid-column spans
};

export const testimonials: Testimonial[] = [
  {
    name: "Sarah Chen",
    role: "Head of Data Engineering",
    company: "Nexus Analytics",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    quote: "FastFlow replaced three different scraping tools for us. The visual workflow builder is leagues ahead of anything else on the market.",
    rating: 5,
    className: "md:col-span-2 md:row-span-2",
  },
  {
    name: "Marcus Rivera",
    role: "CTO",
    company: "DataPulse",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    quote: "The AI prompts feature is genuinely magical. We went from 4 hours of selector maintenance per week to zero. Absolutely zero.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "Aiko Tanaka",
    role: "Growth Lead",
    company: "ScaleUp AI",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    quote: "We monitor over 200 competitor price pages daily. FastFlow handles the complexity effortlessly—and the real-time alerts are a game changer.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "James Okafor",
    role: "Lead Developer",
    company: "Bright Systems",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    quote: "The developer experience is incredible. What used to take days of coding now takes minutes with the drag-and-drop builder.",
    rating: 5,
    className: "md:col-span-2",
  },
  {
    name: "Elena Rostova",
    role: "Data Scientist",
    company: "Alpha Insights",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    quote: "Integrating FastFlow into our ML pipeline was incredibly seamless. The clean data outputs saved our team hundreds of hours.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "David Kim",
    role: "Product Manager",
    company: "RetailWatch",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    quote: "Finally, a tool that lets PMs test scraping logic without pulling engineers away from core tasks.",
    rating: 4,
    className: "md:col-span-1 md:row-span-2",
  },
  {
    name: "Chloe Dubois",
    role: "Marketing Director",
    company: "TrendTracker",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=face",
    quote: "Our competitor analysis is now automated and runs perfectly on schedule. The visual node system makes setting it up literally takes seconds.",
    rating: 5,
    className: "md:col-span-2",
  },
  {
    name: "Omar Farooq",
    role: "Backend Engineer",
    company: "SysTech",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    quote: "Webhooks allow us to pipe data right into our Go microservices effortlessly. It's solid and reliable.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "Priya Patel",
    role: "Founder",
    company: "MarketScout",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    quote: "FastFlow gave our startup the edge it needed to gather data faster than our enterprise competitors. Unbelievable value.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "Liam O'Connor",
    role: "SEO Specialist",
    company: "RankBoost",
    avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&h=150&fit=crop&crop=face",
    quote: "Extracting metadata and analyzing on-page SEO signals across thousands of client pages has never been easier.",
    rating: 5,
    className: "md:col-span-2",
  },
  {
    name: "Maria Hernandez",
    role: "Operations Manager",
    company: "Logistics Pro",
    avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1eb7d0?w=150&h=150&fit=crop&crop=face",
    quote: "We use it to scrape shipping rate adjustments daily. The AI selector automatically adjusts when the target site updates.",
    rating: 5,
    className: "md:col-span-1 md:row-span-2",
  },
  {
    name: "Tom Becker",
    role: "VP of Engineering",
    company: "CloudSync",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&h=150&fit=crop&crop=face",
    quote: "I was skeptical about visual builders, but FastFlow won me over. The architecture is sound and scales beautifully.",
    rating: 5,
    className: "md:col-span-2",
  },
  {
    name: "Nina Ivanova",
    role: "Researcher",
    company: "Global Stats",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    quote: "For large scale academic research, being able to export structured JSON across millions of documents is priceless.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "Jamal Davis",
    role: "Freelance Developer",
    company: "Self-Employed",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&h=150&fit=crop&crop=face",
    quote: "I can deliver web scraping projects to clients 10x faster now. Highly recommended for any consultant.",
    rating: 4,
    className: "md:col-span-1",
  },
  {
    name: "Sophie Clark",
    role: "E-commerce Manager",
    company: "StyleHub",
    avatar: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=150&h=150&fit=crop&crop=face",
    quote: "Tracking competitor inventory and pricing was a nightmare before FastFlow. Now it's a completely automated dashboard.",
    rating: 5,
    className: "md:col-span-2 md:row-span-2",
  },
  {
    name: "Ahmed Rossi",
    role: "Data Analyst",
    company: "FinTech Solutions",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    quote: "The ability to visually map out workflows and then execute them reliably allows us to process financial data seamlessly.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "Lily Wang",
    role: "Software Architect",
    company: "BuildCorp",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    quote: "Clean API, robust execution engine, and zero headache when dealing with dynamic SPA pages. A lifesaver.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "Ethan Wright",
    role: "Creative Director",
    company: "Pixel Agency",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    quote: "Who knew a data tool could be this beautiful? The UI of FastFlow itself is a joy to work with.",
    rating: 5,
    className: "md:col-span-2",
  },
  {
    name: "Zoe Martinez",
    role: "Investment Analyst",
    company: "Capital Partners",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    quote: "We scrape thousands of earnings reports and news snippets daily. FastFlow hasn't failed us once. Totally reliable.",
    rating: 5,
    className: "md:col-span-1",
  },
  {
    name: "Will Thompson",
    role: "Lead QA",
    company: "TechSecure",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    quote: "We even use it for UI testing. Creating visual workflows to simulate user behavior is faster than writing Selenium scripts.",
    rating: 4,
    className: "md:col-span-2",
  }
];
